name:  My-GitHubActions-Basics

on:
  push:
    branches:
      -master
      
jobs:
  my_testing:
  
    runs-on: windows-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello orlWd from Testing job"
  my_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Hello Message
      run: echo "Hello World from Deploy job"
